baudRate = 115200
device = "/dev/ttyUSB0"
movePrefix = "G0"
demoMode = false
windowDimensions = "750x750"
inverseX = false
inverseY = false
offsetX = 0
offsetY = 0
usableX = 410 # Usable space for the toolhead
usableY = 420
usePySerial = true
defaultPositioning = 'absolute'
laserType = 'axon'